### ISSUE TITLE
Add new emojis

### ISSUE THREAD

**Issue by ayrton2510** [MitchTalmadge/Emoji-Tools#22]
Hey Mitch, actually it's not a issue, just a quantion. I'm gonna start modifying the ttf from Android 6.0.1. I'm gonna change it to the ones from Apple. I would like know if it's possible to add and emoji that is not in the original ttf file, like the different skin colors, and how I can do that. I saw the ttx file in the extraction folder. I'm pretty sure I would have to change it to add those emojis. Is that what I really need to do, or maybe I can just add the new pngs to the folder and repackage them??

**Comment by MitchTalmadge** [comment]
The packager works by looking at the definitions in the ttx file and searching for png files that match them by name, so it's not possible to just drop a png file into the directory and have it be added into the font, since the program never looks for it and doesn't know it exists.

I'm not sure of a way to add skin colors to Android Emoji Fonts unfortunately :( I'd love to be able to do so, and I'll do a little research on it, but right now I can't be of help, I'm sorry! If you can find a way to do it, do let me know and I'll add it into the program for everyone else. Thanks!!

**Comment by ayrton2510** [comment]
Yeah, I thought so. Can you take a look at this ttf  from Caio (http://forum.xda-developers.com/android/software-hacking/mod-apple-8-3-diverse-color-emoji-t3136169/post61370793#post61370793)? He was able to add skin modifiers to an android emoji ttf, I compared both ttx, his ttx jus have a lot more lines that include the new emojis. I'm gonna try to work on it. Thanks.

**Comment by MitchTalmadge** [comment]
Yeah, definitely, I'll take a look! Thank you! :) Please let me know if you manage to make it work!

**Comment by ayrton2510** [comment]
This happened now when I was trying to repackage![screenshot 13](https://cloud.githubusercontent.com/assets/16276452/11947211/8cb43f62-a842-11e5-8f94-03c1794efe45.png)

Here is the error report:

BEGIN ERROR REPORT  Version: 1.8 User Name: No Name. User Email: No Email. User Comment: No Comment.  Thread Name: AndroidPackagingThread  BEGIN STACK TRACE  Traceback (most recent call last): File "C:\Users\Ayrton Vasconcelos\Downloads\Emojis\tmp/PythonScripts/package.py", line 4, in   ttx.main(sys.argv[1:]) File "C:\Users\Ayrton Vasconcelos\Downloads\Emojis\tmp\PythonScripts\fontTools\ttx.py", line 353, in main process(jobs, options) File "C:\Users\Ayrton Vasconcelos\Downloads\Emojis\tmp\PythonScripts\fontTools\ttx.py", line 332, in process action(input, output, options) File "C:\Users\Ayrton Vasconcelos\Downloads\Emojis\tmp\PythonScripts\fontTools\ttx.py", line 249, in ttCompile ttf.importXML(input, quiet=options.quiet) File "C:\Users\Ayrton Vasconcelos\Downloads\Emojis\tmp\PythonScripts\fontTools\ttLib\__init__.py", line 344, in importXML reader.read() File "C:\Users\Ayrton Vasconcelos\Downloads\Emojis\tmp\PythonScripts\fontTools\misc\xmlReader.py", line 39, in read self._parseFile(self.file) File "C:\Users\Ayrton Vasconcelos\Downloads\Emojis\tmp\PythonScripts\fontTools\misc\xmlReader.py", line 62, in _parseFile parser.Parse(chunk, 0) File "C:\Users\Ayrton Vasconcelos\Downloads\Emojis\Emoji-Tools.exe\Lib\xml\parsers\expat.py", line 195, in Parse     at java.util.Arrays.copyOf(Unknown Source)     at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)     at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)     at java.lang.AbstractStringBuilder.append(Unknown Source)     at java.lang.StringBuilder.append(Unknown Source)     at java.lang.StringBuilder.append(Unknown Source)     at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)     at java.lang.reflect.Method.invoke(Unknown Source)  java.lang.OutOfMemoryError: java.lang.OutOfMemoryError: Java heap space      at org.python.core.PyException.doRaise(PyException.java:198)     at org.python.core.Py.makeException(Py.java:1337)     at org.python.core.Py.makeException(Py.java:1341)     at org.python.core.Py.makeException(Py.java:1345)     at org.python.core.Py.makeException(Py.java:1349)     at fontTools.ttx$py.main$12(C:\Users\Ayrton Vasconcelos\Downloads\Emojis\tmp\PythonScripts\fontTools\ttx.py:369)     at fontTools.ttx$py.call_function(C:\Users\Ayrton Vasconcelos\Downloads\Emojis\tmp\PythonScripts\fontTools\ttx.py)     at org.python.core.PyTableCode.call(PyTableCode.java:167)     at org.python.core.PyBaseCode.call(PyBaseCode.java:138)     at org.python.core.PyFunction.__call__(PyFunction.java:413)     at org.python.pycode._pyx1.f$0(C:\Users\Ayrton Vasconcelos\Downloads\Emojis\tmp/PythonScripts/package.py:4)     at org.python.pycode._pyx1.call_function(C:\Users\Ayrton Vasconcelos\Downloads\Emojis\tmp/PythonScripts/package.py)     at org.python.core.PyTableCode.call(PyTableCode.java:167)     at org.python.core.PyCode.call(PyCode.java:18)     at org.python.core.Py.runCode(Py.java:1386)     at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)     at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)     at net.liveforcode.EmojiTools.Packaging.PackagingThreads.AndroidPackagingThread.run(AndroidPackagingThread.java:300)  END STACK TRACE END ERROR REPORT

**Comment by ayrton2510** [comment]
Do you have any idea why this just happened?

**Comment by MitchTalmadge** [comment]
It looks like the program ran out of memory. How much RAM do you have installed on your computer? It may be my fault, but I just want to check.

**Comment by ayrton2510** [comment]
8GB.

**Comment by MitchTalmadge** [comment]
Okay, that's definitely enough. Open a command prompt and navigate to the directory where you have the exe (or jar) file. Then run this command:

`java -Xmx2g -jar Emoji-Tools.exe`

(Change exe to jar if you have the jar file)

Hopefully this should let it run. I'll release a small update to fix this soon. Thanks for the report!

**Comment by ayrton2510** [comment]
Got this:
C:\Users\Ayrton Vasconcelos\Downloads\Emojis>java -Xmx2g -jar Emoji-Tools.exe
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

I think it's something with the mod pngs, I extracted stock ttf and repackaged it, and it worked.

**Comment by MitchTalmadge** [comment]
Try replacing 2g with 1g. Also, could you put the modified emojis into a zip file and send it to me? I would be willing to take a look at it! :)

**Comment by ayrton2510** [comment]
Now it worked. I just replaced the stock ones with the ones extracted from the ttf of that XDA thread.

**Comment by MitchTalmadge** [comment]
Alright, I'll take a look at the problem, thank you! Glad you got it working

**Comment by ayrton2510** [comment]
No problem. There's something else, after replacing notocoloremoji.ttf on my Nexus 5, I got only blank spaces. I didn't do the photoshop thing, just replaced the pngs. Don't know if the size is a problem, tomorrow I'm gonna photoshop and see what happens.

**Comment by ayrton2510** [comment]
After resizing all pngs from 160x160 to 128x128, that's what I got.
![screenshot_20151222-084236](https://cloud.githubusercontent.com/assets/16276452/11954633/d92ab204-a888-11e5-85bc-70a92d57d478.png)

**Comment by ayrton2510** [comment]
The problem was the resolution of the pngs. I misread the guide. Some pngs are 136x128. After changing those ones, it all worked. Thanks.

**Comment by ayrton2510** [comment]
Good news. I was able to add an emoji to the ttf.
![screenshot_20151223-103513](https://cloud.githubusercontent.com/assets/16276452/11977404/46ef6536-a961-11e5-9675-18c2361186f5.png)

As you can see, I added the first skin modifier. I wrote some new lines in the android.ttx file, so it could add the new png.

**Comment by MitchTalmadge** [comment]
That's so cool!! Good job!! I'll try to do it myself and hopefully I can add it into Emoji Tools too :)

I actually hope to do a complete redesign of Emojis Tools which will make the entire process a lot easier; less needing to access files and folders, more done in the program itself... For example if you extracted a font, it would then bring you to a page where you can view all the emojis, add and delete them, then when you're done you can press package and all your changes are made. I want to add in a re-sizer too. So this would definitely come in handy.

**Comment by ayrton2510** [comment]
Did you try to add some emojis? I'm gonna start editing to add all the different skins emojis. They work like flags (two letters): Plain emoji + skin modifier = new emoji.

![screenshot_20151224-095733](https://cloud.githubusercontent.com/assets/16276452/11996572/7cd8c73a-aa44-11e5-86d0-569c4413bdeb.png)

**Comment by AnoraxAudio** [comment]
So, exactly how many lines in the android.ttx file did you have to add in order to add a single emoji, and where in the file were the additions needed, if you don't mind me asking? So far I've been trying to get a single font to repackage itself, but since I'm copying files from the standard Noto file (128x128 OR 136x128) into a folder containing the android.ttx from an iOS font (160x160), the new font refuses to repackage.  I guess I'll just have to add the new emojis to the Noto-based android.ttx line-by-line?

**Comment by ayrton2510** [comment]
It's about 5 lines. One of them is actually a group of hundreds of lines. You can also edit the size of pngs.

**Comment by ayrton2510** [comment]
If you have too much files inside thw folder that are not related to any emoji in the ttx file, the program will come up with an error.

**Comment by MrYawnie** [comment]
Hey @ayrton2510 , so which lines did you have to add manually into the TTX file when adding new emojis? And which lines get automatically created during the building process?

**Comment by MrYawnie** [comment]
Actually, I now have added all the other lines except the <rawimagedata> one, the hundreds of lines of raw data. How did you get that data from png, if i may ask? Or did the Emoji Tools create it by itself? @ayrton2510

**Comment by ayrton2510** [comment]
I got them from another font that contains the emoji I wanted to add.

**Comment by ayrton2510** [comment]
@MrYawnie

**Comment by MitchTalmadge** [comment]
Sorry for the long delay on this, but I have good news. I was able to add my own emojis to the google font as you have been able to, and now I am going to program it in so that it will happen automatically any time a new emoji is found.

**Comment by MitchTalmadge** [comment]
This also fixes the crashes experienced any time an emoji is found that is not in the font.ttx file.

**Comment by MrYawnie** [comment]
@ayrton2510 I already figured out how to add any new emojis without copying any code, thanks anyway :) @MitchTalmadge that's awesome! Makes the process a lot simpler, easier and faster than manually doing it.

**Comment by MitchTalmadge** [comment]
@MrYawnie you mean you added new emojis without modifying the ttx file? How did you do that?

**Comment by MrYawnie** [comment]
@MitchTalmadge No, I did modify the ttx file. Just meant that i was able to produce all the code needed, as opposed to ayrton's reply that he copied the code from other font file. As I added completely new fonts (unicode 9 and 10, to be released in summer 2016 and 2017 respectively), there was no other font files i could have copied them from.

**Comment by MitchTalmadge** [comment]
Please try out 1.91 adding Emojis and let me know if it works as intended. Thanks!

**Comment by ayrton2510** [comment]
I'm trying it later this week. The new version adds emojis of any size? 160x160, 128x128?

**Comment by MitchTalmadge** [comment]
Yes, it should be able to add emojis of any size. How they will appear on the phone I am unsure of, but they will at least be added if all goes well.

I wasn't able to get support in this update for glyph substitution emojis (the ones with underscores in their names, flags for example), and you cannot remove emojis, only add them. In a future update I hope to address both of those abilities.

**Comment by ayrton2510** [comment]
Oh, so I can't add ligature emojis?

**Comment by MitchTalmadge** [comment]
Not automatically. You can add the lines in by hand, but I haven't been able to get it working automatically yet.

**Comment by ayrton2510** [comment]
Okay. Yeah. Ligatures need extra lines at the end of the ttx file. There's a category just for ligatures.

**Comment by ayrton2510** [comment]
Hey Mitch, Android N emoji font is out and your latest build is fully capable of extracting all the images from them. If you wanna take a look at them, here you go:
http://android.wonderhowto.com/how-to/get-android-ns-all-new-emojis-right-now-0170328/

**Comment by loki5100** [comment]
hello, I have an ttf font file, and i want to add to it a custom emoji (taken from a png file i already have). Can i do this ? seam ayrton2510 succeed to do it, but i don't understand how he did it ...
