### ISSUE TITLE
Can't pack samsung Flipfont ttf by 1.9.1

### ISSUE THREAD

**Issue by letterb** [MitchTalmadge/Emoji-Tools#28]
Hi, i want to replace some new emojis in this flipfont.  The samsung flipfont may contains the base characters, rather than only contain emojis( This is different from the normal NotoColorEmoji.ttf ). I use Emoji-Tools v1.9.1 to extract the emojis from flipfont normally without any errors. But when i pack the 'ExtractedEmojis' dir( i have not change anything in this dir ), it raise 'Emoji Tools has Crashed!' and show a "Invaild '.ttx' File( Missing PNG File )'---An Emoji that was specified in the '.ttx' file was not found. Packaging cannot continue." 
  i have also try Emoji-Tools 1.8 and 1.9.0, they raise error just while extracting.And i have also execute "java -Xmx2g -jar Emoji-Tools.1.9.1.exe", there is raise the same error in 1.9.1.
This is the Flipfont
  The errors list here:

=======================================
BEGIN ERROR REPORT

Version: 1.91
User Comment: No Comment.

Thread Name: GooglePackagingWorkerThread

BEGIN STACK TRACE

java.lang.NullPointerException at com.mitchtalmadge.emojitools.JythonHandler.close(JythonHandler.java:61) at com.mitchtalmadge.emojitools.operations.OperationWorker.done(OperationWorker.java:110) at java.util.concurrent.FutureTask.finishCompletion(Unknown Source) at java.util.concurrent.FutureTask.set(Unknown Source) at java.util.concurrent.FutureTask.run(Unknown Source) at java.lang.Thread.run(Unknown Source) 
END STACK TRACE
END ERROR REPORT
=======================================
This is the flipfont ttf:

This is the error log:
[error_log.txt](https://github.com/MitchTalmadge/Emoji-Tools/files/487148/error_log.txt)
This is the error screen
![error_screen](https://cloud.githubusercontent.com/assets/16201495/18746812/314ffb50-80fc-11e6-97a8-70093aa1e725.jpg)

**Comment by letterb** [comment]
[Uploading samsung_emoji_twitter.ttf.txt…]()

**Comment by balista22** [comment]
Same problem, Rooting is not an option for me, but I'm using a Samsung on 6.0.1, so without root flipfont let's me change emoji if the installed font has emojis. Right now if I install any recent notocoloremoji.ttf via flipfont the numbers would disappear and there would be no "space" character(I did read some phones cant read . V1.7 was the last version that can package a .ttf and work, except those with modifiers would show up as two characters. Please add a Samsung mode that packages the .ttf with along with all the needed base characters. I've seen emoji font apps on the play store that works with flipfont, i don't know how they packaged it but the flags and modifiers work, see the .ttf files inside "Emoji Plus for Galaxy-Kika"
