### ISSUE TITLE
Unsuccessful decompilation of iOS 10 ttc

### ISSUE THREAD

**Issue by MrYawnie** [MitchTalmadge/Emoji-Tools#29]
I noticed ttc file support has been added to v1.9.2, so i compiled that, and tried it. However, when trying to decompile iOS 10 ttc file, i received the following error log:

`12/14/2016 05:44:10 ip. - INFO: Main GUI Displayed.
12/14/2016 05:44:18 ip. - INFO: Encoding: UTF8
12/14/2016 05:44:46 ip. - INFO: Loading Scripts, Please Wait...
12/14/2016 05:44:46 ip. - INFO: OperationProgressDialog displayed.
12/14/2016 05:44:46 ip. - INFO: Splitting Emoji Font... Please wait...
12/14/2016 05:44:46 ip. - INFO: ****************
12/14/2016 05:44:46 ip. - INFO: **** This may take upwards of 10 minutes.
**** Thank you for your patience.
12/14/2016 05:44:46 ip. - INFO: ****************
12/14/2016 05:44:46 ip. - INFO: Decompiling font 1 of 2 from TTC file...
12/14/2016 05:45:13 ip. - INFO: Compiling Font 1 of 2 into new TTF file...
12/14/2016 05:45:15 ip. - SEVERE: AN ERROR HAS OCCURRED!
12/14/2016 05:45:15 ip. - SEVERE: Thread Name: Thread[AppleSplitterWorkerThread,5,main]
12/14/2016 05:45:15 ip. - SEVERE: Exception:
Traceback (most recent call last):
  File "C:\Users\Jani\Documents\GitHub\Emoji-Tools-new\out\artifacts\Emoji_Tools_jar\tmp/PythonScripts/package.py", line 4, in <module>
    ttx.main(sys.argv[1:])
  File "C:\Users\Jani\Documents\GitHub\Emoji-Tools-new\out\artifacts\Emoji_Tools_jar\tmp\PythonScripts\fontTools\ttx.py", line 398, in main
    sys.exit(1)
SystemExit: 1

	at org.python.core.PySystemState.exit(PySystemState.java:1494)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:478)
	at org.python.core.PyObject.__call__(PyObject.java:482)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at fontTools.ttx$py.main$12(C:\Users\Jani\Documents\GitHub\Emoji-Tools-new\out\artifacts\Emoji_Tools_jar\tmp\PythonScripts\fontTools\ttx.py:398)
	at fontTools.ttx$py.call_function(C:\Users\Jani\Documents\GitHub\Emoji-Tools-new\out\artifacts\Emoji_Tools_jar\tmp\PythonScripts\fontTools\ttx.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.pycode._pyx2.f$0(C:\Users\Jani\Documents\GitHub\Emoji-Tools-new\out\artifacts\Emoji_Tools_jar\tmp/PythonScripts/package.py:4)
	at org.python.pycode._pyx2.call_function(C:\Users\Jani\Documents\GitHub\Emoji-Tools-new\out\artifacts\Emoji_Tools_jar\tmp/PythonScripts/package.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at com.mitchtalmadge.emojitools.operations.splitting.splitters.AppleSplitterWorker.doWork(AppleSplitterWorker.java:90)
	at com.mitchtalmadge.emojitools.operations.OperationWorker.call(OperationWorker.java:64)
	at com.mitchtalmadge.emojitools.operations.OperationWorker.call(OperationWorker.java:29)
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
12/14/2016 05:45:16 ip. - SEVERE: Alert Shown: Extraction Unsuccessful. - Extraction was cancelled or unsuccessful.
12/14/2016 05:45:35 ip. - INFO: Emoji Tools is stopping...
12/14/2016 05:45:35 ip. - INFO: Cleaning up jythonHandler...
12/14/2016 05:45:37 ip. - INFO: Encoding: UTF8
12/14/2016 05:45:38 ip. - SEVERE: AN ERROR HAS OCCURRED!
12/14/2016 05:45:38 ip. - SEVERE: Thread Name: Thread[JavaFX Application Thread,5,main]
12/14/2016 05:45:38 ip. - SEVERE: Exception:
java.io.IOException: Unable to delete file: C:\Users\Jani\Documents\GitHub\Emoji-Tools-new\out\artifacts\Emoji_Tools_jar\tmp\PythonScripts\fontTools\ttLib\tables\_n_a_m_e_test.py
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at com.mitchtalmadge.emojitools.EmojiTools.stop(EmojiTools.java:383)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$163(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
12/14/2016 05:45:38 ip. - INFO: ErrorReportDialog displayed.
`

**Comment by MitchTalmadge** [comment]
Hi @MrYawnie, this appears to be the cause: 

```
Unable to delete file: C:\Users\Jani\Documents\GitHub\Emoji-Tools-new\out\artifacts\Emoji_Tools_jar\tmp\PythonScripts\fontTools\ttLib\tables_n_a_m_e_test.py
```

Try running the program as an administrator and hopefully that will help!

**Comment by MrYawnie** [comment]
This time got this error:
`12/15/2016 05:47:59 ip. - INFO: Main GUI Displayed.
12/15/2016 05:48:06 ip. - INFO: Encoding: UTF8
12/15/2016 05:48:21 ip. - INFO: Loading Scripts, Please Wait...
12/15/2016 05:48:21 ip. - INFO: OperationProgressDialog displayed.
12/15/2016 05:48:21 ip. - INFO: Splitting Emoji Font... Please wait...
12/15/2016 05:48:21 ip. - INFO: ****************
12/15/2016 05:48:21 ip. - INFO: **** This may take upwards of 10 minutes.
**** Thank you for your patience.
12/15/2016 05:48:21 ip. - INFO: ****************
12/15/2016 05:48:21 ip. - INFO: Decompiling font 1 of 2 from TTC file...
12/15/2016 05:48:50 ip. - INFO: Compiling Font 1 of 2 into new TTF file...
12/15/2016 05:48:51 ip. - SEVERE: AN ERROR HAS OCCURRED!
12/15/2016 05:48:51 ip. - SEVERE: Thread Name: Thread[AppleSplitterWorkerThread,5,main]
12/15/2016 05:48:51 ip. - SEVERE: Exception:
Traceback (most recent call last):
  File "C:\Users\Jani\Desktop\EmojiTool\tmp/PythonScripts/package.py", line 4, in <module>
    ttx.main(sys.argv[1:])
  File "C:\Users\Jani\Desktop\EmojiTool\tmp\PythonScripts\fontTools\ttx.py", line 398, in main
    sys.exit(1)
SystemExit: 1

	at org.python.core.PySystemState.exit(PySystemState.java:1494)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:478)
	at org.python.core.PyObject.__call__(PyObject.java:482)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at fontTools.ttx$py.main$12(C:\Users\Jani\Desktop\EmojiTool\tmp\PythonScripts\fontTools\ttx.py:398)
	at fontTools.ttx$py.call_function(C:\Users\Jani\Desktop\EmojiTool\tmp\PythonScripts\fontTools\ttx.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.pycode._pyx2.f$0(C:\Users\Jani\Desktop\EmojiTool\tmp/PythonScripts/package.py:4)
	at org.python.pycode._pyx2.call_function(C:\Users\Jani\Desktop\EmojiTool\tmp/PythonScripts/package.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at com.mitchtalmadge.emojitools.operations.splitting.splitters.AppleSplitterWorker.doWork(AppleSplitterWorker.java:90)
	at com.mitchtalmadge.emojitools.operations.OperationWorker.call(OperationWorker.java:64)
	at com.mitchtalmadge.emojitools.operations.OperationWorker.call(OperationWorker.java:29)
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
12/15/2016 05:48:52 ip. - SEVERE: Alert Shown: Extraction Unsuccessful. - Extraction was cancelled or unsuccessful.
`

**Comment by MrYawnie** [comment]
@MitchTalmadge  So the original issue was gone, but still got the above error when trying to decompile the file. I also tried to recompile other font files, and for some reason, all of them fails with this log.. 

`INFO: Packaged uni261d_uni1f3fe.png
12/16/2016 01:14:34 ip. - INFO: Packaged uni261d_uni1f3ff.png
12/16/2016 01:14:34 ip. - INFO: Packaged uni26f9_uni1f3fb.png
12/16/2016 01:14:36 ip. - INFO: Building font... (This can take a while - Please wait)
12/16/2016 01:14:42 ip. - SEVERE: AN ERROR HAS OCCURRED!
12/16/2016 01:14:42 ip. - SEVERE: Thread Name: Thread[GooglePackagingWorkerThread,5,main]
12/16/2016 01:14:42 ip. - SEVERE: Exception:
Traceback (most recent call last):
  File "C:\Users\Jani\Desktop\EmojiTool\tmp/PythonScripts/package.py", line 4, in <module>
    ttx.main(sys.argv[1:])
  File "C:\Users\Jani\Desktop\EmojiTool\tmp\PythonScripts\fontTools\ttx.py", line 398, in main
    sys.exit(1)
SystemExit: 1

	at org.python.core.PySystemState.exit(PySystemState.java:1494)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:478)
	at org.python.core.PyObject.__call__(PyObject.java:482)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at fontTools.ttx$py.main$12(C:\Users\Jani\Desktop\EmojiTool\tmp\PythonScripts\fontTools\ttx.py:398)
	at fontTools.ttx$py.call_function(C:\Users\Jani\Desktop\EmojiTool\tmp\PythonScripts\fontTools\ttx.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.pycode._pyx1.f$0(C:\Users\Jani\Desktop\EmojiTool\tmp/PythonScripts/package.py:4)
	at org.python.pycode._pyx1.call_function(C:\Users\Jani\Desktop\EmojiTool\tmp/PythonScripts/package.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at com.mitchtalmadge.emojitools.operations.packaging.packagingthreads.GooglePackagingWorker.doWork(GooglePackagingWorker.java:334)
	at com.mitchtalmadge.emojitools.operations.OperationWorker.call(OperationWorker.java:64)
	at com.mitchtalmadge.emojitools.operations.OperationWorker.call(OperationWorker.java:29)
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
12/16/2016 01:14:43 ip. - SEVERE: Alert Shown: Packaging Unsuccessful. - Packaging was cancelled or unsuccessful.
`

**Comment by ezayswift217** [comment]
hi mitch, i try to extract NotoColorEmoji.ttf ios 11.1, it work. but when i packager folder ExtractedEmojis is running for a minutes, but end with error Invalid '.ttx' File (Missing PNG File). look this log.  how to solve this.
[Emoji_Tools.0.0.log](https://github.com/MitchTalmadge/Emoji-Tools/files/1500942/Emoji_Tools.0.0.log)
